version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    expose:
      - 8088
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blockchain
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
